### ISSUE TITLE
The TAB ("\t") charachter

### ISSUE THREAD

**Issue by refaelsh** [jtdaugherty/text-zipper#14]
When I use `insertMany` to insert the following:
```haskell
bla = "1\t2" 
```
I only see `12` on the screen. I expected to see  `1    2`.
But it seems to skip TAB.

**Comment by jtdaugherty** [comment]
Tab is ignored because it is a layout character. I recommend replacing tabs in your input text with the desired number of spaces when inserting into the zipper.

**Comment by refaelsh** [comment]
I understand. It is the expected behavior and not a bug. Thank you.
I will replace my TABs with spaces.
